import { moneyFields } from "../utils/money.js";
import { finiteNumbers } from "../utils/finiteNumbers.js";
import mongoose from "mongoose";
import ExpenseCategory from "./ExpenseCategory.js";
import { validationError } from "../utils/modelValidation.js";

const { Schema } = mongoose;

const expenseSchema = new Schema(
  {
    category: { type: Schema.Types.ObjectId, ref: "ExpenseCategory", required: true },
    amount: { type: Number, required: true, min: 0.01 },
    description: { type: String, trim: true, default: "" },
    expenseDate: { type: Date, default: Date.now },
    recordedBy: { type: Schema.Types.ObjectId, ref: "User", required: true },

    // Set only when this expense was auto-generated by paying a salary
    // (see salaryController.markPaid). Lets a report distinguish salary
    // outflow from other operating expenses, and prevents a salary payment
    // from ever being recorded twice as an expense.
    sourceSalaryPayment: { type: Schema.Types.ObjectId, ref: "SalaryPayment", default: null },
  },
  { timestamps: true }
);

expenseSchema.index({ category: 1, expenseDate: -1 });
expenseSchema.index({ sourceSalaryPayment: 1 }, { unique: true, partialFilterExpression: { sourceSalaryPayment: { $type: "objectId" } } });

// `category` is client-settable directly via the generic CRUD factory
// (POST /api/expenses passes req.body straight to Model.create with no
// dedicated controller in front of it — see routes/expenseRoutes.js), so
// unlike sourceSalaryPayment (only ever set server-side by
// salaryController.markPaid) this one had no guard at all before. Same
// existence-check rationale as FeeInvoice -> student/academicSession.
expenseSchema.pre("validate", async function (next) {
  try {
    if (this.isModified("category")) {
      const exists = await ExpenseCategory.exists({ _id: this.category, archivedAt: null });
      if (!exists) return next(validationError("Referenced category does not exist"));
    }
    next();
  } catch (err) {
    next(err);
  }
});

expenseSchema.plugin(finiteNumbers);
moneyFields(expenseSchema,["amount"]);
export default mongoose.model("Expense", expenseSchema);
